### ISSUE TITLE
Training ERROR After 280 epoches

### ISSUE THREAD

**Issue by yangqu** [vLAR-group/GrowSP#11]
I can run traing script on my our dataset,but after several epoches(total 400) ,sometimes 260,sometimes 280.It throws an exception： 
computing pseduo labels...
Traceback (most recent call last):
  File "train_Custom.py", line 308, in <module>
    main(args, logger)
  File "train_Custom.py", line 121, in main
    train(train_loader, logger, model, optimizer, loss, epoch, scheduler, classifier)
  File "train_Custom.py", line 220, in train
    scheduler.step()
  File "/home/hanson/anaconda3/envs/growsp2/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 152, in step
    values = self.get_lr()
  File "/home/hanson/anaconda3/envs/growsp2/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 1571, in get_lr
    raise ValueError("Tried to step {} times. The specified number of total steps is {}"
ValueError: Tried to step 60002 times. The specified number of total steps is 60000

How can I fix it

**Comment by zhang-zihui** [comment]
hi, @yangqu 
We follow Mix3D to use a OneCycleLR strategy to adjust the learning rate.
![Screenshot from 2023-10-10 20-10-22](https://github.com/vLAR-group/GrowSP/assets/120791554/9d3c3a54-c2f5-4d77-a85f-64807d5d26aa)

This function needs to know the max iteration, your error should be caused by this parameter.
You can compute the number of iterations in an epoch regarding the amount of your dataset and batch size. Then multiply it by the number of epochs you want to train, e.g. 400.
You can alternatively use other strategies for the changing of learning rate.

**Comment by yangqu** [comment]
Thank you very much，it works

**Comment by yangqu** [comment]
And Can I continue to train the model from lastest checkpoint or model-epoch.I can't find the config parameters

**Comment by zhang-zihui** [comment]
Sorry we didn't implement this part, you can add it in the train_SemanticKITTI.py, I believe it is not difficult.
